#!/bin/bash -e

if [[ ${DEBUG} -gt 0 ]]; then set -x; fi

exec 3>&1 # make stdout available as fd 3 for the result
exec &>> /var/log/bash-cni-plugin.log


echo "CNI command: $CNI_COMMAND"

stdin=`cat /dev/stdin`
echo "stdin: $stdin"



case $CNI_COMMAND in
ADD)
    echo $stdin
	network=$(echo "$stdin" | jq -r ".network")
	subnet=$(echo "$stdin" | jq -r ".subnet")
	
    echo "CNI_NETNS: $CNI_NETNS"
	echo "CNI_IFNAME: $CNI_IFNAME"
    echo "CNI_CONTAINERID: $CNI_CONTAINERID"

    exit 0
;;

DEL)
	echo "DELETE"
    exit 0
;;

GET)
	echo "GET not supported"
	exit 1
;;

VERSION)
    echo '{
"cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1", "0.4.0" ] 
}' >&3
    exit 0

;;

*)
  echo "Unknown cni command: $CNI_COMMAND" 
  exit 1
;;

esac