apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cidr-filtering-cni-ds
  namespace: kube-system
  labels:
    tier: node
    app: cidr-filtering-cni
    name: cidr-filtering-cni
spec:
  selector:
    matchLabels:
      name: cidr-filtering-cni
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: cidr-filtering-cni
        name: cidr-filtering-cni
    spec:
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      containers:
      - name: cidr-filtering-cni
        image: quay.io/rhrazdil/cidr-filtering-cni:latest
        command: ["/entrypoint.sh"]
        resources:
          requests:
            cpu: "10m"
            memory: "25Mi"
          limits:
            cpu: "10m"
            memory: "25Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cni
          mountPath: /host/etc/cni/net.d
        - name: cnibin
          mountPath: /host/opt/cni/bin
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
