---
kind: ConfigMap
apiVersion: v1
metadata:
  name: egress-local-network
  namespace: default
  labels:
    cidr-filtering-cni: ""
    br1-with-cidr-filtering: ""
data:
  config.json: |
    {
      "egress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "192.168.0.0/16",
              "except": [
                "192.168.150.0/24",
                "192.168.151.151"
              ]
            }
          }
        ],
        "ports": [
          {
            "protocol": "TCP",
            "port": "80"
          },
          {
            "protocol": "tcp",
            "port": "8080"
          }
        ]
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-network-dhcp
  namespace: default
  labels:
    cidr-filtering-cni: ""
    br1-with-cidr-filtering: ""
data:
  config.json: |
    {
      "egress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "255.255.255.255/32",
              "except": []
            }
          }
        ],
        "ports": [
          {
            "protocol": "udp",
            "port": "67"
          }
        ]
      }
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-local-network
  labels:
    cidr-filtering-cni: ""
    br1-with-cidr-filtering: ""
data:
  config.json: |
    {
      "ingress": {
        "subnets": [
          {
            "subnet": {
              "cidr": "192.168.0.0/16"
            }
          }
        ],
        "ports": []
      }
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: a-configmapped-network
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "br1-with-cidr-filtering",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "br1"
      },
      {
        "type": "cidr-filtering-cni"
      }
    ]
  }'